# Generated by Django 5.1.5 on 2025-04-27 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0003_remove_order_user_favoritecity_delete_item_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteZip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_zips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['zip_code'],
                'unique_together': {('user', 'zip_code')},
            },
        ),
        migrations.DeleteModel(
            name='FavoriteCity',
        ),
    ]
