# Generated by Django 5.1.5 on 2025-04-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0004_favoritezip_delete_favoritecity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritezip',
            options={'ordering': ['city_name']},
        ),
        migrations.AddField(
            model_name='favoritezip',
            name='city_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
